[package]
name = "rssh-win"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.0"
env_logger = "0.11.5"
ssh2 = { version = "0.9.4", features = ["vendored-openssl", "openssl-on-win32"] }
